### ISSUE TITLE
Inconsistency between GCC and ABI

### ISSUE THREAD

**Issue by liqinyang** [LangProc/langproc-2018-cw#17]
In the MIPS ABI, the function having parameter (double, float, float) should use $f12,$f14,$6 to pass its argument.
However, when I use GCC to compile a function having this argument list, it uses $f12,$f14,$7.
I am very confused and don't know what to implement.

C code:
```
int g(double a,float b,float d){
;
}
```
Assembly generated by gcc:
```
        addiu   $sp,$sp,-8
	sw	$fp,4($sp)
	move	$fp,$sp
	swc1	$f12,12($fp)
	swc1	$f13,8($fp)
	swc1	$f14,16($fp)
	sw	$7,20($fp)
	nop
	move	$sp,$fp
	lw	$fp,4($sp)
	addiu	$sp,$sp,8
	j	        $31
	nop
```
<img width="559" alt="image" src="https://user-images.githubusercontent.com/4344894/53767192-eeabd580-3ecc-11e9-8b63-e55864cb269f.png">
MIPS ABI

**Comment by ymherklotz** [comment]
I am not sure if the [MIPS ABI](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf) just does not specify it exactly, or if it is a mistake in the table, but I would follow what GCC is doing as it makes the most sense to me. In the ABI, the paragraph before that table states the following:

> Mapping of this structure into the combination of stack and registers is as follows: up to two leading floating-point  arguments can be passed in $f12 and $f14 everything else with a structure offset greater than or equal to 16 is passed on the stack.

This means that one should think of the arguments that are being passed to the function as a structure and look at the offset to see if it should be in a register or passed in the stack. The offset will also determine which register they will be in. 

| Offset | Register |
|---|---|
| 0 | $4 |
| 4 | $5 |
| 8 | $6 |
| 12 | $7 |

Then, if the argument list starts with floats, you store those in the $f12 and $f14 and then follow the table above for all the over arguments.

In this case, the structure is:

| Offset | Type | Register |
|---|---|---|
| 0 | double | $f12 |
| 8 | float | $f14 |
| 12 | float | $7 (As any more arguments will be >= 16 and therefore go onto the stack). |

Meaning that any more arguments that are passed to the function will have to be passed in the stack. As the last float is aligned at 12, the first table shows that it should go into register $7. I am not quite sure why the table in the ABI says they would store it in $6, and if it is a mistake or if it just is not well defined. However, as GCC seems to be doing that, and you may want to call functions compiled by GCC, it would be best to follow their convention of always putting the values in the register they would be in normally at their specific alignment in the structure.

## Some more examples

```c
int f(float a, int b, int c) {}
```

This expect the arguments in the following registers:

| Offset | Type | Register |
|---|---|---|
| 0 | float | $f12 |
| 4 | int | $5 |
| 8 | int | $6 |

In that case, the function could accept one more argument, which would keep the offset under 16 and could therefore be passed in reg $7. 

Another interesting case which shows the rule above is compiling a function like

```c
int f(double a, float b, double c) {}
```

GCC will put `a` and `b` into registers `$f12` and `f14`, and the last double will have to be passed on the stack. This is because when aligning structures, `double` has to be aligned by 8 bytes.

| Offset | Type | Register |
|---|---|---|
| 0 | double | $f12 |
| 8 | float | $f14 |
| 16 | double (has to be aligned to 16, therefore is passed on the stack). | stack |

**Comment by liqinyang** [comment]
Thank you for your reply. They are really helpful and explain many things, but I still cannot understand one example.
`int f(float a, double b, float c) {}`
My interpretation is 

Offset | Type | Register
-- | -- | --
0 | float | $f12
**4** | double | $f14
12 | float  | $7

However, GCC put the float c on the stack and gives an offset below

Offset | Type | Register
-- | -- | --
0 | float | $f12
**8** | double | $f14
16 | float  | stack

I am not sure why it left an empty word in the stack here.

**Comment by liqinyang** [comment]
Sorry, I read it again and now understand it is because double has to be aligned by 8 bytes.
Thank you for your explain again.

**Comment by BenShen98** [comment]
I had a follow-up question about ABI.

As I was just reading [it](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf) from the link @ymherklotz given, in page 29, it mentioned that 
>The deallocation of the stack frame, which is done by adjusting the stack
pointer value, must occur once and in the last basic block of the function.
The last basic block of a function includes all of the non control-transfer instructions immediately prior to the function exit, including the branch delay slot.

In order to allow stack backtracing and translate already compiled absolute code into position-independent code. 

For this assignment, do we need to generate position-independent code?\
If not, could we move $sp multiple in the same function to allocate and deallocate stack? As it would be much convenient to achieve than per-calculate the total stack space a function is going to take.

**Comment by ymherklotz** [comment]
I believe that you have to be able to generate position-independent code, as even the test bench requires you to assemble your program together with the test bench program which is compiled with GCC. That means that it should adhere to all the conventions in the ABI to work properly with the code compiled by GCC.

You will therefore probably have to precalculate the required stack space.
